# This will update dependencies automatically

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    assignees:
      - "TheLastGimbus"
    reviewers:
      - "TheLastGimbus"
